-
  name: Add DNS server to resov.conf
  hosts: all
  tasks:
    - name: add name server
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver {{ nameserver_ip }}'

    - name: 'Disable SNMP Port'
      firewalld:
        port: "{{ snmp_port }}"
        permanent: true
        state: disabled
