-
  name: Manage services in remote hosts
  hosts: localhost
  remote_user: milclouduser
  become: true
  tasks:
    - name: start mariadb service in a target hosts
      service: name=mariadb.service state=started
    - name: start the httpd service
      service:
        name: httpd
        state: started
    - name: start nginx services
      service:
        name: nginx
        state: started
