---
# tasks file for common_firewalld
- name: Ensure firewalld installed
  yum:
    name: firewalld
    state: installed

- name: Ensure firewalld enabled and started
  service:
    name: firewalld
    enabled: true
    state: started

- name: Manage firewall services
  firewalld:
    zone: public
    service: "{{ item }}"
    state: "{{ service_state }}"
    immediate: true
    permanent: true
  loop: "{{ firewall_services }}"
  notify: reload_firewalld

- name: Manage firewalld service definition
  copy:
    dest: "{{ firewalld_service_path }}/{{ item.value.name | lower }}.xml"
    mode: '0644'
    content: |
      <?xml version="1.0" encoding="utf-8"?>
      <service>
        <short>{{ item.value.name | lower }}</short>
        <description>{{ item.value.name | lower }} service with separate registry.
        Installed by Ansible.</description>
        {% if item.value.ports is defined %}{% for port in item.value.ports %}
        <port port="{{ port.port }}" protocol="{{ port.protocol }}"/>
        {% endfor %}{% endif %}
      </service>
  loop: "{{ lookup('dict', firewall_custom_service,wantlist=True) }}"
  when: firewall_custom_service is defined
  register: install_firewall_service
  notify:
    - reload_firewalld

- name: Flush handlers
  meta: flush_handlers

- debug:
    msg: "{{ install_firewall_service }}"
