---
# defaults file for common_firewalld
firewall_services:
  - http
  - https
firewall_custom_service:
  gitlab:
    name: Gitlab
    ports:
      - port: 80
        protocol: tcp
      - port: 443
        protocol: tcp
      - port: 5050
        protocol: tcp
  mcaffe:
    name: mcaffe
    ports:
      - port: 80
        protocol: tcp
      - port: 443
        protocol: tcp
service_state: enabled
firewalld_service_path: /etc/firewalld/services
